### Get all persons
GET http://localhost:3001/api/persons

### Get a single person
GET http://localhost:3001/api/persons/1

### Delete a person
DELETE http://localhost:3001/api/persons/1

### Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "1234567890"
}

### Get info
GET http://localhost:3001/xxx
